version: '2'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3306:3306"
  ipam:
    depends_on:
      - mysql
    image: pierrecdn/local_phpipam:1.4
    build:
      context: .
      dockerfile: ./Dockerfile.phpipam
    environment:
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_ENV_MYSQL_PASSWORD=my-secret-pw
      - MYSQL_ENV_MYSQL_HOST=mysql
      - MYSQL_ENV_MYSQL_USER=root
    ports:
      - "80:80"
